version: 0.2

phases:
  pre_build:
    commands:
    - echo Entered the pre_build phase...
    - echo $CODEBUILD_SOURCE_VERSION
  build:
    commands:
    - echo Entered the build phase...
    - echo Build started on `date`
    - $(aws ecr get-login --no-include-email --region cn-northwest-1)
    - docker build -t espace:beta .
  post_build:
    commands:
    - echo Entered the post_build phase...
    - echo Build completed on `date`
    - docker tag node-demo:latest 057005827724.dkr.ecr.cn-northwest-1.amazonaws.com.cn/node-demo:latest
    - docker push 057005827724.dkr.ecr.cn-northwest-1.amazonaws.com.cn/espace:latest
    - echo Build Completed
